
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package JsonParser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMMA = 6;
  public static final int DOUBLE = 7;
  public static final int BRACKET_O = 3;
  public static final int error = 1;
  public static final int BRACKET_C = 4;
  public static final int COLON = 5;
  public static final int EOF = 0;
  public static final int CADENA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "BRACKET_O",
  "BRACKET_C",
  "COLON",
  "COMMA",
  "DOUBLE"
  };
}

