
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RCONSOLE = 5;
  public static final int RWRITE = 6;
  public static final int error = 1;
  public static final int PARENTESIS_C = 3;
  public static final int PARENTESIS_A = 2;
  public static final int EOF = 0;
  public static final int CADENA = 7;
  public static final int DOT = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "DOT",
  "RCONSOLE",
  "RWRITE",
  "CADENA"
  };
}

