
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser_statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEMICOLON = 25;
  public static final int CADENA = 28;
  public static final int DOLLAR = 21;
  public static final int RBARRAS = 10;
  public static final int DECIMAL = 30;
  public static final int RGLOBALES = 4;
  public static final int RSTRING = 5;
  public static final int RMAIN = 3;
  public static final int RVARIABLE = 29;
  public static final int RNEWVAL = 7;
  public static final int CURLY_O = 22;
  public static final int RWRITE = 9;
  public static final int RTITULOY = 16;
  public static final int RTITULOX = 15;
  public static final int REJEX = 13;
  public static final int RVALORES = 14;
  public static final int PARENTESIS_O = 17;
  public static final int EQUALS = 24;
  public static final int RVOID = 2;
  public static final int COMMA = 20;
  public static final int CURLY_C = 23;
  public static final int EOF = 0;
  public static final int RTITULO = 11;
  public static final int RDOUBLE = 6;
  public static final int BRACKET_O = 26;
  public static final int DOT = 19;
  public static final int PARENTESIS_C = 18;
  public static final int error = 1;
  public static final int RCONSOLE = 8;
  public static final int RPIE = 12;
  public static final int BRACKET_C = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RVOID",
  "RMAIN",
  "RGLOBALES",
  "RSTRING",
  "RDOUBLE",
  "RNEWVAL",
  "RCONSOLE",
  "RWRITE",
  "RBARRAS",
  "RTITULO",
  "RPIE",
  "REJEX",
  "RVALORES",
  "RTITULOX",
  "RTITULOY",
  "PARENTESIS_O",
  "PARENTESIS_C",
  "DOT",
  "COMMA",
  "DOLLAR",
  "CURLY_O",
  "CURLY_C",
  "EQUALS",
  "SEMICOLON",
  "BRACKET_O",
  "BRACKET_C",
  "CADENA",
  "RVARIABLE",
  "DECIMAL"
  };
}

