
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Parser_statpy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RSTRING = 5;
  public static final int DIFERENT = 53;
  public static final int RWHILE = 33;
  public static final int EQUALS = 41;
  public static final int RDOWHILE = 32;
  public static final int ENTERO = 60;
  public static final int DIVIDED = 47;
  public static final int RVOID = 2;
  public static final int GREATER = 49;
  public static final int RDEFAULT = 28;
  public static final int MINOREQUAL = 50;
  public static final int MINOR = 48;
  public static final int LESS = 45;
  public static final int RELSE = 25;
  public static final int NOT = 43;
  public static final int SEMICOLON = 42;
  public static final int RNEWVAL = 7;
  public static final int COMMA = 37;
  public static final int EQUALEQUAL = 52;
  public static final int RDOUBLE = 6;
  public static final int RCONSOLE = 8;
  public static final int PLUS = 44;
  public static final int DOT = 36;
  public static final int DECIMAL = 59;
  public static final int EOF = 0;
  public static final int BRACKET_O = 54;
  public static final int BY = 46;
  public static final int TRUE = 17;
  public static final int RELIF = 26;
  public static final int error = 1;
  public static final int RBARRAS = 10;
  public static final int CADENA = 57;
  public static final int RWRITE = 9;
  public static final int RTITULO = 11;
  public static final int BREAK = 30;
  public static final int BRACKET_C = 55;
  public static final int PARENTESIS_O = 34;
  public static final int CURLY_O = 39;
  public static final int RCHAR = 22;
  public static final int GREATEREQUAL = 51;
  public static final int COLON = 56;
  public static final int RTITULOY = 16;
  public static final int RTITULOX = 15;
  public static final int RCASE = 29;
  public static final int VARIABLE = 58;
  public static final int PARENTESIS_C = 35;
  public static final int CURLY_C = 40;
  public static final int DOLLAR = 38;
  public static final int RPIE = 12;
  public static final int ROR = 20;
  public static final int RSWITCH = 27;
  public static final int REJEX = 13;
  public static final int RINT = 21;
  public static final int RGLOBALES = 4;
  public static final int RVALORES = 14;
  public static final int FALSE = 18;
  public static final int RFOR = 31;
  public static final int RBOOL = 23;
  public static final int RIF = 24;
  public static final int RAND = 19;
  public static final int RMAIN = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RVOID",
  "RMAIN",
  "RGLOBALES",
  "RSTRING",
  "RDOUBLE",
  "RNEWVAL",
  "RCONSOLE",
  "RWRITE",
  "RBARRAS",
  "RTITULO",
  "RPIE",
  "REJEX",
  "RVALORES",
  "RTITULOX",
  "RTITULOY",
  "TRUE",
  "FALSE",
  "RAND",
  "ROR",
  "RINT",
  "RCHAR",
  "RBOOL",
  "RIF",
  "RELSE",
  "RELIF",
  "RSWITCH",
  "RDEFAULT",
  "RCASE",
  "BREAK",
  "RFOR",
  "RDOWHILE",
  "RWHILE",
  "PARENTESIS_O",
  "PARENTESIS_C",
  "DOT",
  "COMMA",
  "DOLLAR",
  "CURLY_O",
  "CURLY_C",
  "EQUALS",
  "SEMICOLON",
  "NOT",
  "PLUS",
  "LESS",
  "BY",
  "DIVIDED",
  "MINOR",
  "GREATER",
  "MINOREQUAL",
  "GREATEREQUAL",
  "EQUALEQUAL",
  "DIFERENT",
  "BRACKET_O",
  "BRACKET_C",
  "COLON",
  "CADENA",
  "VARIABLE",
  "DECIMAL",
  "ENTERO"
  };
}

